{{- $nautobots := (include "nautobot.nautobots" .) | mustFromJson -}}
{{- $nautobotKeys :=  keys (omit $nautobots "default") | sortAlpha -}}
{{- $nautobotKeys := append $nautobotKeys "default"}}
---
{{- if .Values.route.enabled }}
{{- if .Values.route.gateway.enabled -}}
apiVersion: {{ .Values.route.apiVersion }}
kind: Gateway
metadata:
  name: {{ include "common.names.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if (or .Values.route.annotations .Values.commonAnnotations) }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" (merge .Values.route.annotations .Values.commonAnnotations) "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.route.gateway.gatewayClassName }}
  gatewayClassName: {{ .Values.route.gateway.gatewayClassName | quote }}
  {{- end }}
  listeners:
  - hostname: {{ .Values.route.hostname }}
  {{- if .Values.route.gateway.tls }}
    name: nautobot-local-https
    port: 443
    protocol: HTTPS
    tls:
      mode: Terminate
      certificateRefs:
      - kind: Secret
        name: {{ .Values.route.gateway.secretName }}
  {{- else }}
    name: nautobot-local-http
    port: 80
    protocol: HTTP
  {{- end }}
  {{- if (or .Values.route.gateway.infrastructureLabels .Values.route.gateway.infrastructureAnnotations) }}
  infrastructure:
  {{- if .Values.route.gateway.infrastructureLabels }}
    labels:
      {{- include "common.tplvalues.render" ( dict "value" .Values.route.gateway.infrastructureLabels "context" $ ) | nindent 6 }}
  {{- end }}
  {{- if .Values.route.gateway.infrastructureAnnotations }}
    annotations:
      {{- include "common.tplvalues.render" ( dict "value" .Values.route.gateway.infrastructureAnnotations "context" $ ) | nindent 6 }}
  {{- end }}
  {{- end }}
{{- end }}
---
apiVersion: {{ .Values.route.apiVersion }}
kind: HTTPRoute
metadata:
  name: {{ include "common.names.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if (or .Values.route.annotations .Values.commonAnnotations) }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" (merge .Values.route.annotations .Values.commonAnnotations) "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  hostnames:
    - {{ .Values.route.hostname }}
  {{- if .Values.route.gateway.enabled -}}
  parentRefs:
    - name: {{ include "common.names.fullname" . }}
  {{- else }}
  {{- with.Values.route.parentRefs }}
  parentRefs:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- end }}
  rules:
  - backendRefs:
    - name: nautobot-default
      port: 80
    matches:
    - path:
        type: PathPrefix
        value: /
{{- end }}
