{{- if .Values.nautobot.pdb.create }}
---
apiVersion: {{ include "common.capabilities.policy.apiVersion" . }}
kind: PodDisruptionBudget
metadata:
  name: {{ template "common.names.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: nautobot
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.nautobot.pdb.minAvailable }}
  minAvailable: {{ .Values.nautobot.pdb.minAvailable }}
  {{- end }}
  {{- if .Values.nautobot.pdb.maxUnavailable }}
  maxUnavailable: {{ .Values.nautobot.pdb.maxUnavailable }}
  {{- end }}
  selector:
    matchLabels:
      app.kubernetes.io/component: nautobot
      {{- include "common.labels.matchLabels" . | nindent 6 }}
{{- end }}
{{- if .Values.celeryWorker.pdb.create }}
---
apiVersion: {{ include "common.capabilities.policy.apiVersion" . }}
kind: PodDisruptionBudget
metadata:
  name: {{ template "common.names.fullname" . }}-celery-worker
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: nautobot-celery-worker
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.celeryWorker.pdb.minAvailable }}
  minAvailable: {{ .Values.celeryWorker.pdb.minAvailable }}
  {{- end }}
  {{- if .Values.celeryWorker.pdb.maxUnavailable }}
  maxUnavailable: {{ .Values.celeryWorker.pdb.maxUnavailable }}
  {{- end }}
  selector:
    matchLabels:
      app.kubernetes.io/component: nautobot-celery-worker
      {{- include "common.labels.matchLabels" . | nindent 6 }}
{{- end }}
