{{- if .Values.nautobot.enabled -}}
{{- if .Values.nautobot.persistenceMediaFiles.enabled -}}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "common.names.fullname" $ }}-media
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "common.labels.standard" $ | nindent 4 }}
    app.kubernetes.io/component: nautobot-media-pvc
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" $.Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" $.Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.nautobot.persistenceMediaFiles.storageClassName }}
  {{- if (eq "-" .Values.nautobot.persistenceMediaFiles.storageClassName) }}
  storageClassName: ""
  {{- else }}
  storageClassName: {{ .Values.nautobot.persistenceMediaFiles.storageClassName | quote }}
  {{- end }}
  {{- end }}
  accessModes:
  - {{ .Values.nautobot.persistenceMediaFiles.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.nautobot.persistenceMediaFiles.size | quote }}
  {{- with .Values.nautobot.persistenceMediaFiles.selector }}
  selector:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{ end -}}
{{ end -}}
