---
{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "nautobot.serviceAccountName" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: nautobot
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if (or .Values.serviceAccount.annotations .Values.commonAnnotations) }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" (merge .Values.serviceAccount.annotations .Values.commonAnnotations) "context" $ ) | nindent 4 }}
  {{- end }}
automountServiceAccountToken: false
{{- end }}
