---
name: "Update Dependencies"

on:  # yamllint disable-line rule:truthy
  push:
    paths:
      - "charts/nautobot/Chart.yaml"

jobs:
  update-dependencies:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v4"

      - name: "Set up Helm"
        uses: "azure/setup-helm@v4"

      - name: "Helm Dependency Update"
        run: |
          helm dependency update charts/nautobot

      - name: "Check for changes"
        id: "git-check"
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"
          git diff --quiet || echo "::set-output name=changed::true"

      - name: "Commit changes"
        if: "steps.git-check.outputs.changed == 'true'"
        run: |
          git add .
          git commit -m "chore: Update helm dependencies"
          git push origin ${{ github.ref_name }}
